using System.Collections.Generic;
using System.IO;

namespace FaceLearner.ML.DataSources
{
    /// <summary>
    /// Data source for faces generated by FaceLearner itself
    /// </summary>
    public class GeneratedFaceSource : IFaceDataSource
    {
        private string _capturesDir;
        private string _metadataDir;
        private List<string> _pendingFiles = new List<string>();
        private HashSet<string> _processedIds = new HashSet<string>();
        
        public string Name => "Generated";
        public string Description => "Faces generated by FaceLearner";
        public int TotalCount { get; private set; }
        public int ProcessedCount => _processedIds.Count;
        public bool IsReady { get; private set; }
        
        public bool Initialize(string basePath)
        {
            _capturesDir = Path.Combine(basePath, "Renders");
            _metadataDir = Path.Combine(basePath, "Metadata");
            
            if (!Directory.Exists(_capturesDir))
            {
                Directory.CreateDirectory(_capturesDir);
                Directory.CreateDirectory(_metadataDir);
            }
            
            // Scan for existing files
            _pendingFiles.Clear();
            if (Directory.Exists(_capturesDir))
            {
                foreach (var file in Directory.GetFiles(_capturesDir, "face_*.png"))
                {
                    string baseName = Path.GetFileNameWithoutExtension(file);
                    string jsonFile = Path.Combine(_metadataDir, baseName + ".json");
                    if (File.Exists(jsonFile))
                        _pendingFiles.Add(file);
                }
            }
            
            TotalCount = _pendingFiles.Count;
            IsReady = true;
            return true;
        }
        
        public IEnumerable<FaceSampleInfo> GetBatch(int batchSize)
        {
            int count = 0;
            foreach (var file in _pendingFiles)
            {
                string id = Path.GetFileNameWithoutExtension(file);
                if (_processedIds.Contains(id)) continue;
                
                yield return new FaceSampleInfo
                {
                    Id = id,
                    ImagePath = file,
                    Source = Name
                };
                
                if (++count >= batchSize) break;
            }
        }
        
        public void MarkProcessed(string sampleId)
        {
            _processedIds.Add(sampleId);
        }
        
        public TargetFace GetNextTarget()
        {
            // Generated faces are not used as targets
            // They are outputs, not inputs
            return null;
        }
        
        public void ResetProcessed()
        {
            _processedIds.Clear();
        }
        
        /// <summary>
        /// Get the next capture number for new files
        /// </summary>
        public int GetNextCaptureNumber()
        {
            int max = 0;
            foreach (var file in _pendingFiles)
            {
                string name = Path.GetFileNameWithoutExtension(file);
                if (name.StartsWith("face_") && int.TryParse(name.Substring(5), out int num))
                    max = System.Math.Max(max, num + 1);
            }
            return max;
        }
    }
}
